#############################################################################
# Makefile for building: xgenerationcoin-qt
# Generated by qmake (3.0) (Qt 5.3.0)
# Project:  xgenerationcoin-qt.pro
# Template: app
# Command: c:/Qt/Qt5.3.0/5.3/mingw32-rel-static/bin/qmake.exe -o Makefile xgenerationcoin-qt.pro
#############################################################################

MAKEFILE      = Makefile

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = c:/Qt/Qt5.3.0/5.3/mingw32-rel-static/bin/qmake.exe
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = cp -f
INSTALL_PROGRAM = cp -f
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: xgenerationcoin-qt.pro C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/win32-g++/qmake.conf C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/spec_pre.prf \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/qdevice.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/device_config.prf \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/common/shell-unix.conf \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/qconfig.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_axbase.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_axbase_private.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_axcontainer.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_axcontainer_private.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_axserver.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_axserver_private.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_bluetooth.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_bluetooth_private.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_bootstrap_private.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_clucene_private.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_concurrent.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_concurrent_private.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_core.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_core_private.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_declarative.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_declarative_private.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_designer.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_designer_private.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_designercomponents_private.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_gui.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_gui_private.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_help.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_help_private.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_multimedia.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_multimedia_private.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_multimediawidgets.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_network.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_network_private.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_nfc.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_nfc_private.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_opengl.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_opengl_private.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_openglextensions.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_openglextensions_private.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_platformsupport_private.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_positioning.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_positioning_private.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_printsupport.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_printsupport_private.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_qml.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_qml_private.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_qmltest.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_qmltest_private.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_quick.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_quick_private.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_quickparticles_private.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_quickwidgets.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_script.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_script_private.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_scripttools.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_scripttools_private.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_sensors.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_sensors_private.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_serialport.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_serialport_private.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_sql.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_sql_private.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_svg.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_svg_private.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_testlib.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_testlib_private.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_uitools.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_uitools_private.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_websockets.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_websockets_private.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_widgets.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_widgets_private.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_winextras.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_winextras_private.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_xml.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_xml_private.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_xmlpatterns.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_dsengine.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qdds.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qdeclarativeview.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qicns.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qico.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qjp2.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qminimal.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qmldbg_qtquick2.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qmldbg_tcp_qtdeclarative.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qmng.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qnativewifibearer.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qoffscreen.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qsqlite.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qsqlodbc.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qsvg.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qsvgicon.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qtaccessiblequick.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qtaccessiblewidgets.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qtaudio_windows.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qtga.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qtiff.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qtsensors_dummy.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qwbmp.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qwebp.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qwindows.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_windowsprintersupport.pri \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/qt_functions.prf \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/qt_config.prf \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/win32/qt_config.prf \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/win32-g++/qmake.conf \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/spec_post.prf \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/exclusive_builds.prf \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/default_pre.prf \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/win32/default_pre.prf \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/resolve_config.prf \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/exclusive_builds_post.prf \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/default_post.prf \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/win32/rtti.prf \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/win32/ltcg.prf \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/precompile_header.prf \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/warn_on.prf \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/qt.prf \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/resources.prf \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/moc.prf \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/win32/opengl.prf \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/uic.prf \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/win32/windows.prf \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/testcase_targets.prf \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/exceptions.prf \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/yacc.prf \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/lex.prf \
		xgenerationcoin-qt.pro \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/lib/Qt5Widgets.prl \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/lib/Qt5Gui.prl \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/lib/Qt5Core.prl \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/plugins/accessible/qtaccessiblewidgets.prl \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/plugins/platforms/qwindows.prl \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/lib/Qt5PlatformSupport.prl \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/plugins/imageformats/qdds.prl \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/plugins/imageformats/qicns.prl \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/plugins/imageformats/qico.prl \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/plugins/imageformats/qjp2.prl \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/plugins/imageformats/qmng.prl \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/plugins/imageformats/qtga.prl \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/plugins/imageformats/qtiff.prl \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/plugins/imageformats/qwbmp.prl \
		C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/plugins/imageformats/qwebp.prl
	$(QMAKE) -o Makefile xgenerationcoin-qt.pro
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/spec_pre.prf:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/qdevice.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/device_config.prf:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/common/shell-unix.conf:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/qconfig.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_axbase.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_axbase_private.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_axcontainer.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_axcontainer_private.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_axserver.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_axserver_private.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_bluetooth.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_bluetooth_private.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_bootstrap_private.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_clucene_private.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_concurrent.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_concurrent_private.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_core.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_core_private.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_declarative.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_declarative_private.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_designer.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_designer_private.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_designercomponents_private.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_gui.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_gui_private.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_help.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_help_private.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_multimedia.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_multimedia_private.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_multimediawidgets.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_network.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_network_private.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_nfc.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_nfc_private.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_opengl.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_opengl_private.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_openglextensions.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_openglextensions_private.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_platformsupport_private.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_positioning.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_positioning_private.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_printsupport.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_printsupport_private.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_qml.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_qml_private.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_qmldevtools_private.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_qmltest.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_qmltest_private.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_quick.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_quick_private.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_quickparticles_private.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_quickwidgets.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_quickwidgets_private.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_script.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_script_private.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_scripttools.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_scripttools_private.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_sensors.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_sensors_private.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_serialport.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_serialport_private.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_sql.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_sql_private.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_svg.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_svg_private.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_testlib.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_testlib_private.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_uitools.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_uitools_private.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_websockets.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_websockets_private.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_widgets.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_widgets_private.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_winextras.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_winextras_private.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_xml.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_xml_private.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_xmlpatterns.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_dsengine.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qdds.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qdeclarativeview.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qgenericbearer.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qicns.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qico.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qjp2.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qminimal.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qmldbg_inspector.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qmldbg_qtquick2.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qmldbg_tcp.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qmldbg_tcp_qtdeclarative.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qmng.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qnativewifibearer.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qoffscreen.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qsqlite.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qsqlodbc.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qsvg.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qsvgicon.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qtaccessiblequick.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qtaccessiblewidgets.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qtaudio_windows.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qtga.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qtiff.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qtsensors_dummy.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qtsensors_generic.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qwbmp.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qwebp.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_qwindows.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/modules/qt_plugin_windowsprintersupport.pri:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/qt_functions.prf:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/qt_config.prf:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/win32/qt_config.prf:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/win32-g++/qmake.conf:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/spec_post.prf:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/exclusive_builds.prf:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/default_pre.prf:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/win32/default_pre.prf:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/resolve_config.prf:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/exclusive_builds_post.prf:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/default_post.prf:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/win32/rtti.prf:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/win32/ltcg.prf:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/precompile_header.prf:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/warn_on.prf:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/qt.prf:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/resources.prf:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/moc.prf:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/win32/opengl.prf:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/uic.prf:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/win32/windows.prf:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/testcase_targets.prf:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/exceptions.prf:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/yacc.prf:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/mkspecs/features/lex.prf:
xgenerationcoin-qt.pro:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/lib/Qt5Widgets.prl:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/lib/Qt5Gui.prl:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/lib/Qt5Core.prl:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/plugins/accessible/qtaccessiblewidgets.prl:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/plugins/platforms/qwindows.prl:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/lib/Qt5PlatformSupport.prl:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/plugins/imageformats/qdds.prl:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/plugins/imageformats/qicns.prl:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/plugins/imageformats/qico.prl:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/plugins/imageformats/qjp2.prl:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/plugins/imageformats/qmng.prl:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/plugins/imageformats/qtga.prl:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/plugins/imageformats/qtiff.prl:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/plugins/imageformats/qwbmp.prl:
C:/Qt/Qt5.3.0/5.3/mingw32-rel-static/plugins/imageformats/qwebp.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile xgenerationcoin-qt.pro

qmake_all: FORCE

make_first: release-make_first debug-make_first FORCE
all: release-all debug-all FORCE
clean: release-clean debug-clean FORCE
	-$(DEL_FILE) C:/MinGW/msys/1.0/home/CHH/XGEN_Build/v1.02_dev_1/xgenerationcoin/xgenerationcoin-master/src/leveldb/libleveldb.a;
	-$(DEL_FILE) cd
	-$(DEL_FILE) C:/MinGW/msys/1.0/home/CHH/XGEN_Build/v1.02_dev_1/xgenerationcoin/xgenerationcoin-master/src/leveldb
	-$(DEL_FILE) ;
	-$(DEL_FILE) clean
distclean: release-distclean debug-distclean FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) C:/MinGW/msys/1.0/home/CHH/XGEN_Build/v1.02_dev_1/xgenerationcoin/xgenerationcoin-master/xgenerationcoin-qt_plugin_import.cpp

C:/MinGW/msys/1.0/home/CHH/XGEN_Build/v1.02_dev_1/xgenerationcoin/xgenerationcoin-master/src/leveldb/libleveldb.a: FORCE

release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
